package com.yzidev.analyticsflow.common.enums;

public enum EtlStepName {
	VALIDATE_REQUIRED_FILES,
	IMPORT_USERS_TO_STAGING,
	IMPORT_PRODUCT_CATEGORIES_TO_STAGING,
	IMPORT_PRODUCTS_TO_STAGING,
	IMPORT_PRODUCT_DETAILS_TO_STAGING,
	IMPORT_ORDERS_TO_STAGING,
	IMPORT_ORDER_ITEMS_TO_STAGING,
	IMPORT_TRANSACTIONS_TO_STAGING,
	IMPORT_DELIVERIES_TO_STAGING,
	MIGRATE_MASTER_DATA,
	MIGRATE_ORDER_DATA,
	MIGRATE_TRANSACTION_AND_DELIVERY_DATA,
	TRANSFORM_TO_ANALYTICAL_TABLES,
	GENERATE_INITIAL_REPORT
}
