package com.yzidev.analyticsflow.common.enums;

public enum ReportType {
	SALES_DAILY_SUMMARY,
	SALES_PRODUCT_SUMMARY,
	SALES_CUSTOMER_SUMMARY,
	DELIVERY_PERFORMANCE_SUMMARY,
	PAYMENT_METHOD_SUMMARY,
	CHANNEL_SALES_SUMMARY
}
